[sdwan_edge_nodes]
emea-plant-01-edge ansible_host=10.100.10.1 site=EMEA-Plant-1 vendor=Tata_Kyndryl_MSP
emea-plant-02-edge ansible_host=10.100.20.1 site=EMEA-Plant-2 vendor=Tata_Kyndryl_MSP

[sase_gateways]
ztna-gw-primary ansible_host=10.100.30.15 provider=IBM_Orange_MSSP role=ZTNA-Gateway
ztna-gw-secondary ansible_host=10.100.30.16 provider=IBM_Orange_MSSP role=ZTNA-Gateway

[monitoring_core]
satech-monitoring-core ansible_host=10.100.1.10 role=Prometheus-Grafana-Stack

[satech_nodes:children]
sdwan_edge_nodes
sase_gateways
monitoring_core

[satech_nodes:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/satech-telemetry.pem
ansible_python_interpreter=/usr/bin/python3
